defmodule Mix.Tasks.Exprotoc.Clean do
  use Mix.Task

  @shortdoc "Clean .ex files generated by exprotoc.build"

  @moduledoc """
  mix exprotoc.clean
  """
  def run(args) do
    Mix.Project.get! # Require the project to be available
    Mix.Tasks.Exprotoc.Build.get_output_dir() |> File.rm_rf
  end
end